version: 2.1 
jobs:
   build:
     docker:
       - image: circleci/node:16.13-bullseye-browsers-legacy
     steps:
       - checkout
       - run: export NODE_OPTIONS=--openssl-legacy-provider
       - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
       - run: npm install
       - run: CI=true npm run build
       - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
       - run: npm run test
 
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - test:
          requires:
            - build
